name: negbio2

on: [push]

jobs:
  my-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements3.txt
        python -m nltk.downloader universal_tagset punkt wordnet
    - name: Test with pytest
      env:
        PYTHONPATH: .:$PYTHONPATH
      run: |
        pip install pytest
        pytest
